// Generated by gencpp from file tracking_pid/PidDebug.msg
// DO NOT EDIT!


#ifndef TRACKING_PID_MESSAGE_PIDDEBUG_H
#define TRACKING_PID_MESSAGE_PIDDEBUG_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Twist.h>
#include <geometry_msgs/Twist.h>
#include <geometry_msgs/Twist.h>
#include <geometry_msgs/Twist.h>
#include <geometry_msgs/Twist.h>
#include <geometry_msgs/Twist.h>

namespace tracking_pid
{
template <class ContainerAllocator>
struct PidDebug_
{
  typedef PidDebug_<ContainerAllocator> Type;

  PidDebug_()
    : error()
    , proportional()
    , integral()
    , derivative()
    , feedforward()
    , raw_error()
    , scale_long_control(0.0)  {
    }
  PidDebug_(const ContainerAllocator& _alloc)
    : error(_alloc)
    , proportional(_alloc)
    , integral(_alloc)
    , derivative(_alloc)
    , feedforward(_alloc)
    , raw_error(_alloc)
    , scale_long_control(0.0)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::Twist_<ContainerAllocator>  _error_type;
  _error_type error;

   typedef  ::geometry_msgs::Twist_<ContainerAllocator>  _proportional_type;
  _proportional_type proportional;

   typedef  ::geometry_msgs::Twist_<ContainerAllocator>  _integral_type;
  _integral_type integral;

   typedef  ::geometry_msgs::Twist_<ContainerAllocator>  _derivative_type;
  _derivative_type derivative;

   typedef  ::geometry_msgs::Twist_<ContainerAllocator>  _feedforward_type;
  _feedforward_type feedforward;

   typedef  ::geometry_msgs::Twist_<ContainerAllocator>  _raw_error_type;
  _raw_error_type raw_error;

   typedef float _scale_long_control_type;
  _scale_long_control_type scale_long_control;





  typedef boost::shared_ptr< ::tracking_pid::PidDebug_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::tracking_pid::PidDebug_<ContainerAllocator> const> ConstPtr;

}; // struct PidDebug_

typedef ::tracking_pid::PidDebug_<std::allocator<void> > PidDebug;

typedef boost::shared_ptr< ::tracking_pid::PidDebug > PidDebugPtr;
typedef boost::shared_ptr< ::tracking_pid::PidDebug const> PidDebugConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::tracking_pid::PidDebug_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::tracking_pid::PidDebug_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::tracking_pid::PidDebug_<ContainerAllocator1> & lhs, const ::tracking_pid::PidDebug_<ContainerAllocator2> & rhs)
{
  return lhs.error == rhs.error &&
    lhs.proportional == rhs.proportional &&
    lhs.integral == rhs.integral &&
    lhs.derivative == rhs.derivative &&
    lhs.feedforward == rhs.feedforward &&
    lhs.raw_error == rhs.raw_error &&
    lhs.scale_long_control == rhs.scale_long_control;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::tracking_pid::PidDebug_<ContainerAllocator1> & lhs, const ::tracking_pid::PidDebug_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace tracking_pid

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::tracking_pid::PidDebug_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tracking_pid::PidDebug_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tracking_pid::PidDebug_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tracking_pid::PidDebug_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tracking_pid::PidDebug_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tracking_pid::PidDebug_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::tracking_pid::PidDebug_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9e084788031037458fcbdc7432057e27";
  }

  static const char* value(const ::tracking_pid::PidDebug_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9e08478803103745ULL;
  static const uint64_t static_value2 = 0x8fcbdc7432057e27ULL;
};

template<class ContainerAllocator>
struct DataType< ::tracking_pid::PidDebug_<ContainerAllocator> >
{
  static const char* value()
  {
    return "tracking_pid/PidDebug";
  }

  static const char* value(const ::tracking_pid::PidDebug_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::tracking_pid::PidDebug_<ContainerAllocator> >
{
  static const char* value()
  {
    return "geometry_msgs/Twist error\n"
"geometry_msgs/Twist proportional\n"
"geometry_msgs/Twist integral\n"
"geometry_msgs/Twist derivative\n"
"geometry_msgs/Twist feedforward\n"
"geometry_msgs/Twist raw_error\n"
"float32 scale_long_control\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Twist\n"
"# This expresses velocity in free space broken into its linear and angular parts.\n"
"Vector3  linear\n"
"Vector3  angular\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Vector3\n"
"# This represents a vector in free space. \n"
"# It is only meant to represent a direction. Therefore, it does not\n"
"# make sense to apply a translation to it (e.g., when applying a \n"
"# generic rigid transformation to a Vector3, tf2 will only apply the\n"
"# rotation). If you want your data to be translatable too, use the\n"
"# geometry_msgs/Point message instead.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::tracking_pid::PidDebug_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::tracking_pid::PidDebug_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.error);
      stream.next(m.proportional);
      stream.next(m.integral);
      stream.next(m.derivative);
      stream.next(m.feedforward);
      stream.next(m.raw_error);
      stream.next(m.scale_long_control);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PidDebug_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::tracking_pid::PidDebug_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::tracking_pid::PidDebug_<ContainerAllocator>& v)
  {
    s << indent << "error: ";
    s << std::endl;
    Printer< ::geometry_msgs::Twist_<ContainerAllocator> >::stream(s, indent + "  ", v.error);
    s << indent << "proportional: ";
    s << std::endl;
    Printer< ::geometry_msgs::Twist_<ContainerAllocator> >::stream(s, indent + "  ", v.proportional);
    s << indent << "integral: ";
    s << std::endl;
    Printer< ::geometry_msgs::Twist_<ContainerAllocator> >::stream(s, indent + "  ", v.integral);
    s << indent << "derivative: ";
    s << std::endl;
    Printer< ::geometry_msgs::Twist_<ContainerAllocator> >::stream(s, indent + "  ", v.derivative);
    s << indent << "feedforward: ";
    s << std::endl;
    Printer< ::geometry_msgs::Twist_<ContainerAllocator> >::stream(s, indent + "  ", v.feedforward);
    s << indent << "raw_error: ";
    s << std::endl;
    Printer< ::geometry_msgs::Twist_<ContainerAllocator> >::stream(s, indent + "  ", v.raw_error);
    s << indent << "scale_long_control: ";
    Printer<float>::stream(s, indent + "  ", v.scale_long_control);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TRACKING_PID_MESSAGE_PIDDEBUG_H
