; Auto-generated. Do not edit!


(cl:in-package tracking_pid-msg)


;//! \htmlinclude FollowPathResult.msg.html

(cl:defclass <FollowPathResult> (roslisp-msg-protocol:ros-message)
  ()
)

(cl:defclass FollowPathResult (<FollowPathResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <FollowPathResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'FollowPathResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name tracking_pid-msg:<FollowPathResult> is deprecated: use tracking_pid-msg:FollowPathResult instead.")))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <FollowPathResult>) ostream)
  "Serializes a message object of type '<FollowPathResult>"
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <FollowPathResult>) istream)
  "Deserializes a message object of type '<FollowPathResult>"
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<FollowPathResult>)))
  "Returns string type for a message object of type '<FollowPathResult>"
  "tracking_pid/FollowPathResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'FollowPathResult)))
  "Returns string type for a message object of type 'FollowPathResult"
  "tracking_pid/FollowPathResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<FollowPathResult>)))
  "Returns md5sum for a message object of type '<FollowPathResult>"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'FollowPathResult)))
  "Returns md5sum for a message object of type 'FollowPathResult"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<FollowPathResult>)))
  "Returns full string definition for message of type '<FollowPathResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#result definition~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'FollowPathResult)))
  "Returns full string definition for message of type 'FollowPathResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#result definition~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <FollowPathResult>))
  (cl:+ 0
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <FollowPathResult>))
  "Converts a ROS message object to a list"
  (cl:list 'FollowPathResult
))
