; Auto-generated. Do not edit!


(cl:in-package tracking_pid-msg)


;//! \htmlinclude FollowPathFeedback.msg.html

(cl:defclass <FollowPathFeedback> (roslisp-msg-protocol:ros-message)
  ((progress
    :reader progress
    :initarg :progress
    :type cl:float
    :initform 0.0))
)

(cl:defclass FollowPathFeedback (<FollowPathFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <FollowPathFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'FollowPathFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name tracking_pid-msg:<FollowPathFeedback> is deprecated: use tracking_pid-msg:FollowPathFeedback instead.")))

(cl:ensure-generic-function 'progress-val :lambda-list '(m))
(cl:defmethod progress-val ((m <FollowPathFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader tracking_pid-msg:progress-val is deprecated.  Use tracking_pid-msg:progress instead.")
  (progress m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <FollowPathFeedback>) ostream)
  "Serializes a message object of type '<FollowPathFeedback>"
  (cl:let ((bits (roslisp-utils:encode-single-float-bits (cl:slot-value msg 'progress))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <FollowPathFeedback>) istream)
  "Deserializes a message object of type '<FollowPathFeedback>"
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
    (cl:setf (cl:slot-value msg 'progress) (roslisp-utils:decode-single-float-bits bits)))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<FollowPathFeedback>)))
  "Returns string type for a message object of type '<FollowPathFeedback>"
  "tracking_pid/FollowPathFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'FollowPathFeedback)))
  "Returns string type for a message object of type 'FollowPathFeedback"
  "tracking_pid/FollowPathFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<FollowPathFeedback>)))
  "Returns md5sum for a message object of type '<FollowPathFeedback>"
  "70805092fd20e110765c7b79e8efb737")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'FollowPathFeedback)))
  "Returns md5sum for a message object of type 'FollowPathFeedback"
  "70805092fd20e110765c7b79e8efb737")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<FollowPathFeedback>)))
  "Returns full string definition for message of type '<FollowPathFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#feedback~%float32 progress~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'FollowPathFeedback)))
  "Returns full string definition for message of type 'FollowPathFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#feedback~%float32 progress~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <FollowPathFeedback>))
  (cl:+ 0
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <FollowPathFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'FollowPathFeedback
    (cl:cons ':progress (progress msg))
))
